site_name: Big Neuronal Data Format
site_url: https://gitlab.com/neuroscience-lab/bndf

theme:
  name: mkdocs
  nav_style: dark
  highlightjs: true
  collapse_navigation: true
  titles_only: true
  hljs_languages:
    - yaml
    - rust
    - bash
    - text
    - scala
    - sql